### ISSUE TITLE
Account for Camunda Modeler 5 changes. 

### ISSUE THREAD

**Issue by Skaiir** [sharedchains/camunda-modeler-plugin-multidiagram#14]
Hello, Valentin from Camunda here.

With Camunda Modeler 5.0.0 we are making some changes to how we handle plugins.

First off, our docs have moved here https://docs.camunda.io/docs/components/modeler/desktop-modeler/plugins/.

In short, plugins now work for cloud bpmn-js diagrams, and will automatically be picked up without any changes.

If your plugin does not make sense on (or isn't yet compatible with) cloud diagrams, you'll have to use the new plugin registration helper functions that were shipped in https://github.com/camunda/camunda-modeler-plugin-helpers v5.0.0 - i.e replacing `registerBpmnJSPlugin` with `registerPlatformBpmnJSPlugin` - to opt out. Note that this will be breaking.

Otherwise, if it would conceptually work on cloud, and functionally there's nothing platform specific in your code, you don't have to do anything. Although I recommend testing using one of our recent modeler builds to make sure the application does not crash. 

I'm only going to raise one issue across the sharedchains org, but this applies to all plugins. 

Feel free to ask anything about this 😄. If you come across any problems please relay them back to us as soon as possible.

**Comment by Ichigo85** [comment]
Hello @Skaiir ! I just started in these days to update our plugins, I made a new branch for v5.0.0 [here](https://github.com/sharedchains/camunda-modeler-plugin-multidiagram/tree/feature/modeler-5.0), feel free to check it out!
I tried to replace `registerBpmnJSPlugin` with `registerPlatformBpmnJSPlugin` and make some combinations, if it works on Platform, it doesn't work on Cloud (giving me an error) and viceversa. There is no way I can make this plugin available on both platform and cloud?
Also, I have some problems with the new properties panel. I tried to update it following the [bpmn-js-example](https://github.com/bpmn-io/bpmn-js-examples/tree/master/properties-panel-extension) but I have a preact error that I don't understand. 
Could you suggest me the right direction?

**Comment by Skaiir** [comment]
If you want the plugin available on both platform and cloud, just keep using registerBpmnJSPlugin and the latest versions of Modeler will pick the plugin up for both :)

I'll have a look into the properties panel stuff a little later today.
Can you provide your error below?

All the best,
Val.

**Comment by Ichigo85** [comment]
Sure! When I have my  registered Properties Provider enabled and I just select an element I receive this error
```
preact.module.js:1 Uncaught (in promise) TypeError: Cannot read property 'is' of undefined
    at R (preact.module.js:1)
    at A (preact.module.js:1)
    at O (preact.module.js:1)
    at R (preact.module.js:1)
    at A (preact.module.js:1)
    at O (preact.module.js:1)
    at R (preact.module.js:1)
    at A (preact.module.js:1)
    at O (preact.module.js:1)
    at A (preact.module.js:1)
<!--StartFragment-->

  | R | @ | preact.module.js:1
-- | -- | -- | --
  | A | @ | preact.module.js:1
  | O | @ | preact.module.js:1
  | R | @ | preact.module.js:1
  | A | @ | preact.module.js:1
  | O | @ | preact.module.js:1
  | R | @ | preact.module.js:1
  | A | @ | preact.module.js:1
  | O | @ | preact.module.js:1
  | A | @ | preact.module.js:1
  | (anonymous) | @ | preact.module.js:1
  | w | @ | preact.module.js:1
  | Promise.then (async) |   |  
  | x | @ | preact.module.js:1
  | y.setState | @ | preact.module.js:1
  | o.__c.o.__ | @ | hooks.module.js:1
  | (anonymous) | @ | index.esm.js:249
  | k | @ | hooks.module.js:1
  | (anonymous) | @ | hooks.module.js:1
  | P | @ | hooks.module.js:1
  | setTimeout (async) |   |  
  | n | @ | hooks.module.js:1
  | requestAnimationFrame (async) |   |  
  | (anonymous) | @ | hooks.module.js:1
  | a.options.diffed | @ | hooks.module.js:1
  | A | @ | preact.module.js:1
  | O | @ | preact.module.js:1
  | R | @ | preact.module.js:1
  | A | @ | preact.module.js:1
  | O | @ | preact.module.js:1
  | R | @ | preact.module.js:1
  | A | @ | preact.module.js:1
  | O | @ | preact.module.js:1
  | A | @ | preact.module.js:1
  | O | @ | preact.module.js:1
  | R | @ | preact.module.js:1
  | A | @ | preact.module.js:1
  | O | @ | preact.module.js:1
  | R | @ | preact.module.js:1
  | A | @ | preact.module.js:1
  | O | @ | preact.module.js:1
  | A | @ | preact.module.js:1
  | O | @ | preact.module.js:1
  | A | @ | preact.module.js:1
  | O | @ | preact.module.js:1
  | A | @ | preact.module.js:1
  | O | @ | preact.module.js:1
  | A | @ | preact.module.js:1
  | O | @ | preact.module.js:1
  | A | @ | preact.module.js:1
  | (anonymous) | @ | preact.module.js:1
  | w | @ | preact.module.js:1
  | Promise.then (async) |   |  
  | x | @ | preact.module.js:1
  | y.setState | @ | preact.module.js:1
  | o.__c.o.__ | @ | hooks.module.js:1
  | g | @ | index.esm.js:1341
  | e | @ | index.esm.js:1361
  | (anonymous) | @ | EventBus.js:519
  | Ne._invokeListener | @ | EventBus.js:371
  | Ne._invokeListeners | @ | EventBus.js:352
  | Ne.fire | @ | EventBus.js:313
  | en.select | @ | Selection.js:106
  | (anonymous) | @ | SelectionBehavior.js:99
  | (anonymous) | @ | EventBus.js:519
  | Ne._invokeListener | @ | EventBus.js:371
  | Ne._invokeListeners | @ | EventBus.js:352
  | Ne.fire | @ | EventBus.js:313
  | s | @ | InteractionEvents.js:94
  | f.<computed> | @ | InteractionEvents.js:173
  | (anonymous) | @ | index.esm.js:359

<!--EndFragment-->
```

**Comment by Ichigo85** [comment]
Hello @Skaiir , I tried to move my code on the new panel properties example and everything works, it's probably a problem with the latest version of Camunda Modeler that needs to be recompiled. Thank you very much!
